finalProject/finalProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projectApp.urls', namespace="maxrs")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalProject/projectApp/urls.py
from django.urls import path
from . import views

app_name = "projectApp"
urlpatterns = [
    path('', views.getHome.as_view(), name="home"),
    path('visual', views.getIndex.as_view(), name="visual"),
    path('visual/form', views.VisualizeForm.as_view(), name="visual_from_db"),
    path('visual/view', views.VisualizeData.as_view(), name="visual_view_db"),
    path('login', views.getLogin.as_view(), name="login"),
    path('register', views.getSignUp.as_view(), name="register"),
    path('coordinate', views.coordinate.as_view(), name="coordinate"),
    path('import/object',views.AddObject.as_view(), name="add_object"),
    path('create/object',views.getForm.as_view(), name="create"),
    path('create/junction',views.JunctionAdd.as_view(), name="JunctionAdd"),
    path('import/junction', views.JunctionImport.as_view(), name="JunctionImport"),
    path('import/area', views.AreaImport.as_view(), name="AreaImport"),
    path('logout',views.LogOut.as_view(), name="logout"),

    path('docs', views.getDocs.as_view(template_name='documentation.html'), name="Documents"),
    path('doc/<slug>', views.Document.as_view(template_name='single_doc.html'), name="SingleDoc"),
]

finalProject/projectApp/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db.models.signals import pre_save
from django.utils.text import slugify
# Create your models here.
class SpatialData(models.Model):
    district=models.CharField(max_length=100)
    thana=models.CharField(max_length=100)
    post_office=models.CharField(max_length=100)
    type=models.CharField(max_length=100)
    level=models.CharField(max_length=100)
    code=models.CharField(max_length=100)
    name=models.CharField(max_length=100)
    address=models.TextField()
    mobile=models.CharField(max_length=100)
    management=models.CharField(max_length=100)
    gender_type=models.CharField(max_length=100)
    area_type=models.CharField(max_length=100)
    geography=models.CharField(max_length=100)
    no_of_male=models.IntegerField(default=0, null=True, blank=True)
    no_of_female=models.IntegerField(default=0,null=True, blank=True)
    total=models.IntegerField(default=0, null=True, blank=True)
    longitude=models.CharField(max_length=50)
    lattitude=models.CharField(max_length=50)
    high_income=models.DecimalField(max_digits=10, decimal_places=5)
    mid_income=models.DecimalField(max_digits=10, decimal_places=5)
    low_income=models.DecimalField(max_digits=10, decimal_places=5)
    def __str__(self):
        return self.name.title()

class Junction(models.Model):
    name=models.CharField(max_length=200)
    longitude = models.CharField(max_length=12)
    lattitude = models.CharField(max_length=12)

    def __str__(self):
        return self.name

class AreaInfo(models.Model):
    thana = models.CharField(max_length=200)
    population = models.IntegerField()
    area_size=models.DecimalField(max_digits=5, decimal_places=2)
    def __str__(self):
        return self.thana

class Documentation(models.Model):
    title=models.CharField(max_length=200)
    body=RichTextField()
    slug=models.SlugField(unique=True, blank=True, null=True)
    def __str__(self):
        return self.title.title()

def create__slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    s = Documentation.objects.filter(slug=slug).order_by("-id")
    exist = s.exists()
    if exist:
        new_slug = "%s-%s" % (slug, s.first().id)
        return create__slug(instance, new_slug=new_slug)
    return slug


def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create__slug(instance)


pre_save.connect(pre_save_receiver, sender=Documentation)

finalProject/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block meta %}
    {% endblock %}
    <title>{% block title %}

    {% endblock %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.8/css/mdb.min.css" rel="stylesheet">
    <style>
        .carousel,.carousel .carousel-inner,.carousel .carousel-inner .active,.carousel .carousel-inner .carousel-item,.view,body,html{height:100%}.navbar{background-color:rgba(0,0,0,.7)}.page-footer,.top-nav-collapse{background-color:#1C2331}@media only screen and (max-width:768px){.navbar{background-color:#1C2331}}
        @media (min-width: 800px) and (max-width: 850px) {
              .navbar:not(.top-nav-collapse) {
                  background: #1C2331!important;
              }
          }
          header {
            margin-bottom: 30px!important;
        }
    </style>
    {% block stylesheet %}

    {% endblock %}
</head>
<body>
    <header style="height: 40px;">
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand" href="{% url 'maxrs:home' %}">
        <strong>MaxRS</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect waves-light" href="{% url 'maxrs:visual' %}">Visual from CSV
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle waves-effect waves-light" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Spatial Object
            </a>
            <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item waves-effect waves-light" href="{% url 'maxrs:add_object' %}">Import from CSV</a>
              <a class="dropdown-item waves-effect waves-light" href="{% url 'maxrs:create' %}">Create new object</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle waves-effect waves-light" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Junction
            </a>
            <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item waves-effect waves-light" href="{% url 'maxrs:JunctionImport' %}">Import from CSV</a>
              <a class="dropdown-item waves-effect waves-light" href="{% url 'maxrs:JunctionAdd' %}">Create new junction</a>
            </div>
          </li>
        <li class="nav-item">
            <a class="nav-link waves-effect waves-light" href="{% url 'maxrs:Documents' %}">Documentation</a>
        </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a href="" class="nav-link waves-effect waves-light">
              <i class="fa fa-facebook-f"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="" class="nav-link waves-effect waves-light">
              <i class="fa fa-twitter"></i>
            </a>
          </li>

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle border border-light rounded waves-effect waves-light" id="navbarDropdownMenuLink-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  <i class="fa fa-user-md mr-2"></i> Profile </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                  {% if request.user.is_superuser %}
                      <a class="dropdown-item waves-effect waves-light" href="/admin">Go to admin</a>
                  {% endif %}
                  <a class="dropdown-item waves-effect waves-light" href="{% url 'maxrs:logout' %}">Log out</a>
                </div>
              </li>
                {% else %}
                <li class="nav-item">
                <a href="{% url 'maxrs:login' %}" class="nav-link border border-light rounded waves-effect waves-light">
                  <i class="fa fa-sign-in mr-2"></i>Login
                </a></li>
            {% endif %}
        </ul>

      </div>

    </div>
  </nav>
    </header>
        {% block content %}
        {% endblock %}

    <!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.8/js/mdb.min.js"></script>
{% block script %}

{% endblock %}
</body>
</html>

finalProject/templates/coordinate.html
{% extends 'base.html' %}
    {% block stylesheet %}

        <link rel="stylesheet" href="https://js.arcgis.com/4.8/esri/css/main.css">

        <style>
        html, body, #viewDiv {
          padding: 0;
          margin: 0;
          height: 100%;
          width: 100%;
        }
        .content {
        width: 100%;
        height: 100%;
        display: flex;
        }
        .info{
          width: 20%;
        }
        </style>


    {% endblock %}
{% block content %}
    <div class="content">
        <div id="viewDiv"></div>
        <div class="info">
            <h1>Description: </h1>
            <div class="info1" style="display: flex;padding: 10px;"><span style="width: 15px; height: 15px; background: rgb(226, 119, 40); border-radius: 50%;margin-top: 5px;"></span><span>: Existing school</span></div>
        </div>
    </div>
{% endblock %}

{% block script %}
<script src="https://js.arcgis.com/4.8/"></script>
        <script>
        let lon=[];
        let lat=[];
    require([
		  "esri/Map",
		  "esri/views/MapView",
		  //*** ADD ***//
		  "esri/Graphic",
		  "esri/geometry/Point",
		  "esri/symbols/SimpleMarkerSymbol",
		  "dojo/domReady!"
		], function(Map, MapView,
		      //*** ADD ***//
		      Graphic, Point, SimpleMarkerSymbol
		) {

      let map = new Map({
        basemap: "topo-vector"
      });

      let view = new MapView({
	    container: "viewDiv",
	    map: map,
	    //*** ADD ***//
	    center: [90.3564612,23.7872745],
	    zoom: 12
	  });
      //*** ADD ***//
	  // Create a point


    {% for ins in institute %}
        $.getJSON('https://maps.googleapis.com/maps/api/geocode/json?address={{ ins }}&key=AIzaSyA43-pm17h9AYwodjdvqYMVXc3z60BaJX0', function(data) {
            lon.push(data.results[0].geometry.location.lng);
            lat.push(data.results[0].geometry.location.lat);
        });
    {% endfor %}



	  // Create a symbol for drawing the point
	  let markerSymbol = new SimpleMarkerSymbol({
	    color: [226, 119, 40],
	    outline: {
	      color: [255, 255, 255],
	      width: 1
	    }
	  });

	  // Create a graphic and add the geometry and symbol to it
	  for (let i = 0; i < lat.length; i++) {
	  	let point = new Point({
		    longitude: lon[i],
		    latitude: lat[i]
		  });
	  	let graphic_point = new Graphic({
		    geometry: point,
		    symbol: markerSymbol
		  });
	  	view.graphics.add(graphic_point);
	  }
    });
  </script>
{% endblock %}

finalProject/templates/documentation.html
{% extends 'base.html' %}
{% block meta %}

{% endblock %}
{% block title %}SpatialDB documentation{% endblock %}
{% block stylesheet %}
    <style>
    header {
    height: 0px!important;
    margin-bottom: 0px!important;
}
    .carousel{
    height: 300px;
}
    .page-wrapper{
        margin-top: 20px;
    }
    .single-doc{
        margin-top: 10px;
    }
    </style>
{% endblock %}
{% block content %}
    {% load staticfiles %}
<!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade"  data-ride="carousel">


    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">

        <div class="view" style="background-image: url('https://s3.amazonaws.com/dev.assets.neo4j.com/wp-content/uploads/20160414124341/spatial-data-graph-visualization-approach.png'); background-repeat: no-repeat; background-size: cover;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light d-flex justify-content-center align-items-center">
            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h3><strong>Documentation</strong></h3>
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
      </div>
      <!--/First slide-->




    </div>
    <!--/.Slides-->
  </div>
    <div class="page-wrapper">
        <div class="container">
            <div class="docs-main">
                {% for documentation in documentation_list %}
                    <div class="card single-doc">
                    <div class="card-body">
                        <h3 class="card-title"><a href="{% url 'maxrs:SingleDoc' documentation.slug %}">{{ documentation.title.capitalize }}</a></h3>
                        <p>{{ documentation.body|safe|truncatewords:50 }}</p>
                    </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

finalProject/templates/form.html
{% extends 'base.html' %}
{% block title %}
    Add a new object
{% endblock %}
{% block meta %}
{% endblock %}
{% block stylesheet %}
{% endblock %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card border-primary mb-3">
              <div class="card-header text-center text-white bg-primary mb-3">
                <h3>Create a new object</h3>
              </div>
              <div class="card-body">
                <form action="" method="POST">
                {% csrf_token %}
                    <h5 class="p-2 mb-2 bg-info text-white">Address info</h5>
                    <div class="row">
                        <div class="col-md-6">{{ form.district|as_crispy_field  }}</div>
                        <div class="col-md-6">{{ form.thana|as_crispy_field  }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.post_office|as_crispy_field  }}</div>
                        <div class="col-md-6">{{ form.code|as_crispy_field  }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">{{ form.address|as_crispy_field  }}</div>
                    </div>
                    <h5 class="p-2 mb-2 bg-info text-white">Basic info</h5>
                    <div class="row">
                        <div class="col-md-6">{{ form.name|as_crispy_field  }}</div>
                        <div class="col-md-6">{{ form.type|as_crispy_field  }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.level|as_crispy_field  }}</div>
                        <div class="col-md-6">{{ form.management|as_crispy_field  }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.gender_type|as_crispy_field  }}</div>
                        <div class="col-md-6">{{ form.area_type|as_crispy_field  }}</div>
                    </div>
                    <h5 class="p-2 mb-2 bg-info text-white">Geographical info</h5>
                    <div class="row">
                        <div class="col-md-4">{{ form.geography|as_crispy_field  }}</div>
                        <div class="col-md-4">{{ form.longitude|as_crispy_field  }}</div>
                        <div class="col-md-4">{{ form.lattitude|as_crispy_field  }}</div>
                    </div>
                    <h5 class="p-2 mb-2 bg-info text-white">Ratio of different income families</h5>
                    <div class="row">
                        <div class="col-md-4">{{ form.high_income|as_crispy_field  }}</div>
                        <div class="col-md-4">{{ form.mid_income|as_crispy_field  }}</div>
                        <div class="col-md-4">{{ form.low_income|as_crispy_field  }}</div>
                    </div>
                    <h5 class="p-2 mb-2 bg-info text-white">Contact info</h5>
                    <div class="row">
                        <div class="col-md-12">{{ form.mobile|as_crispy_field  }}</div>
                    </div>
                    <h5 class="p-2 mb-2 bg-info text-white">No of male and female student info</h5>
                    <div class="row">
                        <div class="col-md-4">{{ form.no_of_male|as_crispy_field  }}</div>
                        <div class="col-md-4">{{ form.no_of_female|as_crispy_field  }}</div>
                        <div class="col-md-4">{{ form.total|as_crispy_field  }}</div>
                    </div>
                <div class="text-center">
                    <button class="btn btn-primary">Add object</button>
                    <button type="reset" class="btn btn-danger">Reset</button>
                    <a id="sample" class="btn btn-default">Sample input</a>
                </div>
                </form>
              </div>
              <div class="card-footer text-muted">
                  <a href="">Follow the instructions to add new object</a>
              </div>
            </div>

        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}
{% block script %}
    <script>
    $(document).ready(function () {
        $("#sample").click(function (event) {
            $('#id_district').val("Dhaka");
            $('#id_thana').val("Mohammadpur");
            $('#id_post_office').val("Adabor");
            $('#id_code').val("1210");
            $('#id_address').val("Full address of the object. e.g: House 12-A, Humayun Road");
            $('#id_name').val("Name of the institute");
            $('#id_type').val("School or College");
            $('#id_level').val("Secondary or Higher secondery");
            $('#id_gender_type').val("Boys or Girls or Co-education");
            $('#id_area_type').val("City Corporation");
            $('#id_geography').val("Plainland");
            $('#id_longitude').val("94.245864");
            $('#id_lattitude').val("23.54521");
            $('#id_high_income').val("0.15");
            $('#id_mid_income').val("0.26");
            $('#id_low_income').val("0.59");
            $('#id_mobile').val("01763433XXX");
            $('#id_no_of_male').val("254");
            $('#id_no_of_female').val("562");
            $('#id_total').val("816");
            $('#id_management').val("Private or Public");
        });
    });
    </script>
{% endblock %}

finalProject/templates/home.html
{% extends 'base.html' %}
{% block meta %}

{% endblock %}
{% block title %}
Welcome to our final project show.
{% endblock %}
{% block stylesheet %}
    <style>
        header {
            margin-bottom: 150px!important;
        }
            @media (max-width: 780px){
                header{
                    margin-bottom: 50px!important;
                }
            }
    </style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'maxrs:visual' %}"><h1>Visualize from CSV</h1></a>
            <p>It will not important to store the spatial data in the database. Rather you can upload a csv file in a fixed format and view the maximizing range sum based on your data. You must follow the data format from <a href="">here</a> </p>
        </div>
        <div class="col-md-6">
            <a href="{% url 'maxrs:visual_from_db' %}"> <h1>Visualize from existing data</h1> </a>
            <p>Database contains large amount of spatial data with different parameter. You can use them to see the maximizing range sum. You can also add new spatial data related to school, college, hospital etc from
                <a href="{% url 'maxrs:create' %}">here</a> or you also can import the csv file to store in database from <a href="{% url 'maxrs:add_object' %}">here</a></p>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}

{% endblock %}

finalProject/templates/login.html
{% extends 'base.html' %}
{% block meta %}

{% endblock %}
{% block title %}
    Login to get more options
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- Material form login -->
        <div class="card">

          <h5 class="card-header info-color white-text text-center py-4">
            <strong>Sign in</strong>
          </h5>

          <!--Card content-->
          <div class="card-body px-lg-5 pt-0">

            <!-- Form -->
            <form action="" method="POST" class="text-center" style="color: #757575;">
                {% csrf_token %}
              <!-- Username -->
              <div class="md-form">
                <input type="text" name="username" id="id_username" class="form-control">
                <label for="id_username">Username</label>
                  <p class="user-txt text-left"></p>
              </div>

              <!-- Password -->
              <div class="md-form">
                <input type="password" name="password" id="id_password" class="form-control">
                <label for="id_password">Password</label>
                  <p class="pass-txt text-left"></p>
              </div>

              <div class="d-flex justify-content-around">
                <div>
                  <!-- Forgot password -->
                  <a href="">Forgot password?</a>
                </div>
              </div>

              <!-- Sign in button -->
              <button class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0" id="loginBtn">Log In</button>

              <!-- Register -->
              <p>Not a member?
                <a href="{% url 'maxrs:register' %}">Register</a>
              </p>

            </form>
            <!-- Form -->

          </div>

        </div>
        <!-- Material form login -->
    </div>
    <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
        $("#loginBtn").click(function (event) {
             let id_username=$('#id_username');
             let id_password=$('#id_password');


            if (id_username.val()==''){
                id_username.addClass('invalid');
                id_username.next('label').addClass('text-danger').removeClass('text-success');
                $('.user-txt').html('<p class="text-danger">Field is required</p>');
                event.preventDefault();
            } else{
                id_username.removeClass('invalid').addClass('valid');
                id_username.next('label').removeClass('text-danger').addClass('text-success');
                $('.user-txt').html('');
            }
            if (id_password.val()==''){
                id_password.addClass('invalid');
                id_password.next('label').addClass('text-danger').removeClass('text-success');
                $('.pass-txt').html('<p class="text-danger">Field is required</p>');
                event.preventDefault();
            } else{
                id_password.removeClass('invalid').addClass('valid');
                id_password.next('label').removeClass('text-danger').addClass('text-success');
                $('.pass-txt').html('');
            }
        });
    });
    </script>
{% endblock %}

finalProject/templates/register.html
{% extends 'base.html' %}
{% block title %}
    Add a new object
{% endblock %}
{% block meta %}
{% endblock %}
{% block stylesheet %}
{% endblock %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card border-success mb-3">
              <div class="card-header text-center text-white bg-success mb-3">
                <h3>Create a new account</h3>
              </div>
              <div class="card-body">
                <form action="" method="POST">
                {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">{{ form.first_name|as_crispy_field  }}</div>
                        <div class="col-md-6">{{ form.last_name|as_crispy_field  }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.username|as_crispy_field  }}</div>
                        <div class="col-md-6">{{ form.email|as_crispy_field  }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.password1|as_crispy_field  }}</div>
                        <div class="col-md-6">{{ form.password2|as_crispy_field  }}</div>
                    </div>
                <div class="text-center">
                    <button class="btn btn-primary">Create account</button>
                </div>
                    <p>Already registered?
                        <a href="{% url 'maxrs:login' %}">Login</a>
                      </p>
                </form>
              </div>
            </div>

        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

finalProject/templates/sample.html
{% extends 'base.html' %}
{% block meta %}

{% endblock %}
{% block title %}

{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block content %}

{% endblock %}
{% block script %}

{% endblock %}

finalProject/templates/single_doc.html
{% extends 'base.html' %}
{% block meta %}

{% endblock %}
{% block title %}
documentation: {{ documentation.title }}
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block content %}
    <div class="page-wrapper">
    <div class="container">
        <div class="df">
            <h1>{{ documentation.title.capitalize }}</h1>
            <p>{{ documentation.body|safe }}</p>
        </div>
    </div>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

finalProject/templates/visual_form.html
{% extends 'base.html' %}
{% block meta %}

{% endblock %}
{% block title %}
    View the spatial max range sum from stored data
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header purple lighten-1 white-text">Expecting best possible school location using MaxRS</div>
        <div class="card-body">
            <form action="{% url 'maxrs:visual_view_db' %}" method="GET">

            <div class="form-group" id="type-group">
                <label for="type">Select type:</label>
                    <select name="type" id="type" class="form-control">
                        <option value="">-------</option>
                        {% for l in level %}
                            <option value="{{ l }}">{{ l.title }}</option>
                        {% endfor %}

                    </select>
                <div class="alert-txt"></div>
            </div>
            <div class="form-group" id="area-group">
                <label for="area">Area:</label>
                    <select name="area" id="area" class="form-control">
                        <option value="">-------</option>
                        {% for t in thana %}
                            <option value="{{ t }}">{{ t.title }}</option>
                        {% endfor %}

                    </select>
                <div class="area-text"></div>
            </div>
            <div class="form-group" id="management-group">
                <label for="management">Management:</label>
                    <select name="management" id="management" class="form-control">
                        <option value="">-------</option>
                        {% for m in management %}
                            <option value="{{ m }}">{{ m.title }}</option>
                        {% endfor %}
                    </select>
                <div class="management-text"></div>
            </div>
            <div class="form-group" id="area-group">
                <label for="area_type">Area type:</label>
                    <select name="area_type" id="area_type" class="form-control">
                        <option value="">-------</option>
                        {% for a in area_type %}
                            <option value="{{ a }}">{{ a.title }}</option>
                        {% endfor %}
                    </select>
                <div class="area_type-text"></div>
            </div>
            <div class="form-group" id="geography-group">
                <label for="geography">Geography of object:</label>
                    <select name="geography" id="geography" class="form-control">
                        <option value="">-------</option>
                        {% for g in geography %}
                            <option value="{{ g }}">{{ g.title }}</option>
                        {% endfor %}
                    </select>
                <div class="geography-text"></div>
            </div>
                <input type="hidden" name="map_type" value="topo-vector">
            <div class="form-group">
                <button type="reset" class="btn btn-primary">Reset</button>
                <button class="btn btn-success" id="go">GO</button>
            </div>

        </form>
        </div>
    </div>

</div>
{% endblock %}
{% block script %}

{% endblock %}